name: Upload Python Package

on:
  push:
    #paths: 'pyproject.toml'
    tags: [ 'v*.*.*' ]
permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI via token
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYP_TOKEN }}
          packages-dir: dist/

  sbom-publish:
    runs-on: ubuntu-latest
    needs: pypi-publish

    steps:         
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cyclonedx-bom

      - name: Generate SBOM from all installed packages
        run: |
          pip freeze > requirements.txt
          cyclonedx-py requirements -i requirements.txt -o sbom.xml

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X POST "${{ secrets.API_URL }}/api/v1/bom" \
            -H "X-Api-Key: ${{ secrets.API_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "project=${{ secrets.PROJECY_ID }}" \
            -F "bom=@sbom.xml"