name: Upload Python Package

on:
  push:
    paths: 'pyproject.toml'

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI via token
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYP_TOKEN }}
          packages-dir: dist/

  sbom-publish:
    runs-on: ubuntu-latest
    needs: release-build

    steps:
      - name: SBOM Generation and upload
        uses: AppThreat/cdxgen-action@v1
        with:
          output: "./reports/bom.xml"
          serverUrl: "https://vbulletin-sink-strongly-directive.trycloudflare.com/"
          apiKey: ${{ secrets.DEPTRACK_TOKEN }}