name: unitTests sonarQ and  depCheck
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Build release distributions
          run: |
            python -m pip install build
            python -m build

    sonarqube:
        name: SonarQube cloud
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python }}
            - name: Install tox
              run: pip install tox
            - name: Run tox
              run: tox -e py
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    dependency-check:
      needs: sonarqube
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run OWASP Dependency-Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: jsSecrets
            path: .
            format: HTML
            out: reports
            args: >
              --failOnCVSS 1
              --enableExperimental
              --enableRetired
              --scan ./src
              --noupdate

        - name: Upload report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: dependency-check-report
            path: reports/dependency-check-report.html